### ISSUE TITLE
Why config.json?

### ISSUE THREAD

**Issue by MrQUACKK** [JavaCafe01/despicable#1]
Why do u decode json instead of just using `botkey` as a global variable in a file like `config.lua`? Wouldn't that be more efficient? 
BTW I mean you would do something like this:

`config.lua`:
```lua
botkey = "BOT_KEY"
```
`bot.lua`:
```lua
local config = require "config.lua"
```
I could make a PR with this change if u want :)

**Comment by MrQUACKK** [comment]
Ok we had a discussion on `#bot` in the server and it seems that local variables in `bot.lua` makes the most sense

**Comment by JavaCafe01** [comment]
Fixed in #4
